### ISSUE TITLE
请上传一下数据，谢谢

### ISSUE THREAD

**Issue by ybxgood** [wepe/TianChi-Industry4.0-Competition#1]
没有找到数据

**Comment by wepe** [comment]
数据太大了，请到赛题官网下载

**Comment by hadoop73** [comment]
官网只有6组数据，你这儿9组数据
下面数据并没有啊
- 新测试数据，`draft_data_test_new.csv`, `param_data_test_new.csv`, `timevarying_param_test_new.csv`

**Comment by wepe** [comment]
更换过数据，不用这数据也没关系，反正测试集不知道标签。可以只用训练集看效果

**Comment by lunarfire** [comment]
您好，我今天才看到这道题，但是在官网下载数据的时候，提示淘盘于2017年6月1日以后不再提供对应的下载服务，这样我就拿不到原始数据了。请问您可以将比赛数据放到百度网盘或者某个方便下载的地方吗？谢谢。

**Comment by wepe** [comment]
没有哦
